Examples update for Dataset-JSON v1.1
cdisc-org/DataExchange-DatasetJson pull request #28
Opened 2024-07-30 19:16 UTC by lexjansen

Updates for ADaM, SDTM, and SEND.

- ADaM examples implement sending numeric dates as ISO 8601 strings (with displayFormat E8601DA.
- Also, ADaM examples implement decimal transfer according to the following logic (just as an example!!)
`  
if xml_datatype in ('float' 'integer') and
     dataset_name in ('ADADAS' 'ADLBC' 'ADLBCPV' 'ADLBH' 'ADLBHPV' 'ADLBHY' 'ADNPIX' 'ADSL' 'ADVS') and
     name in ('PCHG' 'AVAL' 'BASE' 'CHG' 'PCHG' 'R2A1LO' 'R2A1HI' 'BR2A1LO' 'BR2A1HI' 'A1LO' 'A1HI' 'R2A1LO' 'R2A1HI' 'ALBTRVAL' 'LBSTRESN' 'HEIGHTBL' 'WEIGHTBL')
     then do;
      dataType='decimal';
      targetDataType='decimal';
    end;
`
- SDTM and SEND examples have decimal transfers, mostly for --STRESN

2024-07-31 15:33 UTC, gerrycampion requested changes

2024-07-31 15:33 UTC, gerrycampion commented on examples/adam/adadas.json
Are you going to update the ndjson files?

2024-07-31 15:33 UTC, gerrycampion commented on examples/sdtm/ae.json
General question - I see, for example, that dataset-json floats and ints are stored as json numbers and dataset-json decimals are stored as json strings. Are these mappings documented somewhere or in the schema?

2024-07-31 15:49 UTC, lexjansen commented on examples/sdtm/ae.json
See the specification: https://wiki.cdisc.org/display/DSJSON1DOT1/Dataset-JSON+1.1. To preserve precision there is an option to transfer fractional numbers as decimals. The specification does not describe when that option should be used.

2024-07-31 15:50 UTC, lexjansen commented on examples/adam/adadas.json
Sam is updating the ndjson files.

2024-07-31 18:16 UTC, lexjansen commented
The sourceSystem name and version properties in the examples are not right. I will update them.

2024-08-01 02:40 UTC, swhume commented
I converted the previously committed examples to NDJSON and validated them. They looked good. I will re-run the conversion with this latest commit. Should be good to approve by tomorrow.

2024-08-01 20:50 UTC, lexjansen commented
Updates for ADaM, SDTM, and SEND.

- ADaM examples implement sending numeric dates as ISO 8601 strings (with displayFormat E8601DA.)
- Also, ADaM examples implement decimal transfer according to the following logic (just as an example!!)
  `  
if dataset_name in ('ADLBC' 'ADLBH') and 
     name in ('PCHG' 'AVAL' 'BASE' 'CHG' 'PCHG' 'A1LO' 'A1HI' 'R2A1LO' 'R2A1HI' 'BR2A1LO' 'BR2A1HI' 'ALBTRVAL' 'LBSTRESN')
     then do;
      dataType='decimal';
      targetDataType='decimal';
 end;
`

2024-08-04 01:43 UTC, swhume approved these changes
Successfully reviewed, validated, and converted the examples.

2024-08-04 01:45 UTC, swhume commented on examples/adam/adadas.json
I have converted the examples to NDJSON and will create a PR to add them

2024-08-04 01:49 UTC, merged